name: "[Reusable] Labeled Preview"

on:
  workflow_call:
    inputs:
      branch:
        type: string
        required: true

jobs:
  new-labeled-deployment:
    name: "Deployment"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch `${{ github.head_ref }}`
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub actions"
          git config user.email noreply@github.com

      - name: Set `${{ inputs.branch }}` to `${{ github.head_ref }}`
        run: |
          git checkout -b ${{ inputs.branch }}
          git push origin ${{ inputs.branch }} --tags --force
